name: Deploy to VPS

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install SSH key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.VPS_DEPLOY_KEY }}

    - name: Deploy to VPS
      run: |
        ssh -o StrictHostKeyChecking=no ${{  secrets.VPS_USER }}@${{ secrets.VPS_IP }} << 'EOF'
          cd /home/${{ secrets.VPS_USER }}/todo_list_front/
          git pull origin master
          npm install   
          npm run build 
          sudo cp -r /home/${{ secrets.VPS_USER }}/todo_list_front/build/* /var/www/todo_list
        EOF